### ISSUE TITLE
Replacing eaf with moocore

### ISSUE THREAD

**Issue by MLopez-Ibanez** [relund/gMOIP#10]
Dear Lars,

I am planning to retire the `eaf` package and separate its functionality into two packages: [`moocore`](https://multi-objective.github.io/moocore/r/), which will have very few dependencies, and [`mooplot`](https://multi-objective.github.io/mooplot/r/), which will handle plotting and interactivity.

In your case, it will be a matter of replacing `eaf` by `moocore` since the same function [`is_nondominated`](https://multi-objective.github.io/moocore/r/reference/nondominated.html) is in `moocore`. 

It will still take a few months to get `moocore` into CRAN, but I wanted to let you know in advance.

**Comment by relund** [comment]
Thanks. I have updated the package.
