### ISSUE TITLE
Does vertices argument to inHull() need to give a convex hull?

### ISSUE THREAD

**Issue by scottkosty** [relund/gMOIP#6]
The help for `inHull()` says the following:

```
vertices: A mxp array of vertices of the convex hull.
```

If `vertices` is not a convex hull, does `inHull()` then convert it to be a convex hull?

**Comment by relund** [comment]
Vertices define the convex hull but may contain redundant (non-vertex) points.

Doc updated

**Comment by scottkosty** [comment]
Thanks, the documentation is clear. If my goal is to check whether a point is in the convex hull of a set of vertices, is it faster to first use `convexHull()` and then take that result and call `inHull()`? The advantage of this is that there would be no redundant points in the call to `inHull()`. I can run tests to see myself, but I'm also curious about your recommendation.

**Comment by relund** [comment]
Most of the time the algorithm for finding the convex hull is called one time. So it should not make a difference. It would make a difference if you call the algorithm multiple times with different pts but the same hull.

**Comment by scottkosty** [comment]
> Most of the time the algorithm for finding the convex hull is called one time. So it should not make a difference. It would make a difference if you call the algorithm multiple times with different pts but the same hull.

Thanks!
